### ISSUE TITLE
HACS installed Card no longer shows in Lovelace

### ISSUE THREAD

**Issue by Kurisutian** [panbachi/tankerkoenig-card#5]
I installed the tankerkoenig-card using HACS and it worked fine already. 
But somehow something changed and all I can get is the error `Custom element doesn't exist: tankerkoenig-card.` 
I uninstalled and installed the card again with HACS but still lovelace only shows the error and not the card any longer.

**Comment by BlackP999** [comment]
I found the solution!
The tankerkoenig-card is not longer a JS Type. It's a module!
Change in the rescources from Type JS to MODULE.

**Comment by jaegerschnitzel** [comment]
I also have a similar problem. I installed custom tankerkoenig-card via HACS. Ressources should be loaded fine because I don’t have any errors:
![grafik](https://user-images.githubusercontent.com/4368865/147859820-d0bb3e64-5e3b-4294-8b60-e0afa807b7ba.png)

I cannot see the Lovelace card and adding manually does also not work.
